export const dataFood = [
  {
    id: 1,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 2,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 3,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 4,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 5,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 6,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 7,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 8,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 9,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 10,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 11,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
  {
    id: 12,
    name: "Rice",
    image: "/rice.jpg",
    des: "Vietnamese Food is better and yummy",
    basePrice: "$20",
    sizes: "30 mm",
    extraIngredientPrices: "$60",
  },
];
